# Generated by Django 5.1.7 on 2026-03-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название клуба')),
                ('short_name', models.CharField(default='Газпром', max_length=80, verbose_name='Короткое имя')),
                ('tagline', models.CharField(max_length=255, verbose_name='Слоган')),
                ('mission', models.TextField(verbose_name='Описание клуба')),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('stadium', models.CharField(max_length=120, verbose_name='Стадион')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('vk_url', models.URLField(blank=True, verbose_name='VK')),
                ('hero_badge', models.CharField(default='Газпром трансгаз Томск', max_length=120, verbose_name='Hero badge')),
                ('stats_wins', models.PositiveIntegerField(default=18, verbose_name='Победы за сезон')),
                ('stats_goals', models.PositiveIntegerField(default=52, verbose_name='Голы')),
                ('stats_clean_sheets', models.PositiveIntegerField(default=9, verbose_name='Матчи на ноль')),
            ],
            options={
                'verbose_name': 'Профиль клуба',
                'verbose_name_plural': 'Профиль клуба',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('category', models.CharField(choices=[('matchday', 'Matchday'), ('training', 'Training'), ('community', 'Community')], max_length=20)),
                ('caption', models.CharField(max_length=255, verbose_name='Подпись')),
                ('image', models.ImageField(blank=True, upload_to='gallery/', verbose_name='Изображение')),
                ('accent', models.CharField(blank=True, max_length=80, verbose_name='Акцентный текст')),
            ],
            options={
                'verbose_name': 'Медиа-элемент',
                'verbose_name_plural': 'Медиа-элементы',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opponent', models.CharField(max_length=160, verbose_name='Соперник')),
                ('competition', models.CharField(max_length=160, verbose_name='Турнир')),
                ('start_at', models.DateTimeField(verbose_name='Дата матча')),
                ('venue', models.CharField(max_length=160, verbose_name='Площадка')),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('status', models.CharField(choices=[('upcoming', 'Скоро'), ('live', 'Live'), ('finished', 'Завершен')], default='upcoming', max_length=12)),
                ('score_for', models.PositiveIntegerField(blank=True, null=True, verbose_name='Голы Газпрома')),
                ('score_against', models.PositiveIntegerField(blank=True, null=True, verbose_name='Голы соперника')),
                ('summary', models.TextField(blank=True, verbose_name='Краткий обзор')),
                ('featured', models.BooleanField(default=False, verbose_name='Выделить')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('body', models.TextField(verbose_name='Текст')),
                ('cover', models.ImageField(blank=True, upload_to='news/', verbose_name='Обложка')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160, verbose_name='Имя')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('position', models.CharField(choices=[('GK', 'Вратарь'), ('DF', 'Защитник'), ('MF', 'Полузащитник'), ('FW', 'Нападающий')], max_length=2, verbose_name='Позиция')),
                ('captain', models.BooleanField(default=False, verbose_name='Капитан')),
                ('hometown', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('bio', models.TextField(verbose_name='Профиль игрока')),
                ('achievements', models.CharField(blank=True, max_length=255, verbose_name='Достижения')),
                ('photo', models.ImageField(blank=True, upload_to='players/', verbose_name='Фото')),
                ('speed', models.PositiveIntegerField(default=80)),
                ('stamina', models.PositiveIntegerField(default=80)),
                ('technique', models.PositiveIntegerField(default=80)),
                ('featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['sort_order', 'number', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='Трофей')),
                ('season', models.CharField(max_length=50, verbose_name='Сезон')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Трофей',
                'verbose_name_plural': 'Трофеи',
                'ordering': ['-season', 'title'],
            },
        ),
    ]
