# Generated by Django 5.1.7 on 2026-03-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='source_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Источник данных'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='URL источника'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='remote_image_url',
            field=models.URLField(blank=True, verbose_name='Внешнее изображение'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='source_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='URL источника'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_logo_url',
            field=models.URLField(blank=True, verbose_name='Лого соперника'),
        ),
        migrations.AddField(
            model_name='match',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Источник матча'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='remote_cover_url',
            field=models.URLField(blank=True, verbose_name='Внешняя обложка'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='source_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='URL источника'),
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='player',
            name='citizenship',
            field=models.CharField(blank=True, max_length=120, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_for_club',
            field=models.PositiveIntegerField(default=0, verbose_name='Голы за клуб'),
        ),
        migrations.AddField(
            model_name='player',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост (см)'),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_for_club',
            field=models.PositiveIntegerField(default=0, verbose_name='Матчи за клуб'),
        ),
        migrations.AddField(
            model_name='player',
            name='minutes_for_club',
            field=models.PositiveIntegerField(default=0, verbose_name='Минуты за клуб'),
        ),
        migrations.AddField(
            model_name='player',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=160, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_club',
            field=models.CharField(blank=True, max_length=160, verbose_name='Предыдущий клуб'),
        ),
        migrations.AddField(
            model_name='player',
            name='red_cards',
            field=models.PositiveIntegerField(default=0, verbose_name='Красные карточки'),
        ),
        migrations.AddField(
            model_name='player',
            name='remote_photo_url',
            field=models.URLField(blank=True, verbose_name='Внешнее фото'),
        ),
        migrations.AddField(
            model_name='player',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Источник игрока'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_cards',
            field=models.PositiveIntegerField(default=0, verbose_name='Жёлтые карточки'),
        ),
        migrations.AlterField(
            model_name='match',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Профиль игрока'),
        ),
    ]
