# Generated by Django 5.1.7 on 2026-03-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_clubprofile_source_name_clubprofile_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='hospitality_url',
            field=models.URLField(blank=True, verbose_name='Hospitality'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='membership_url',
            field=models.URLField(blank=True, verbose_name='Абонементы'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='shop_url',
            field=models.URLField(blank=True, verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='ticket_url',
            field=models.URLField(blank=True, verbose_name='Билеты'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='hero_badge',
            field=models.CharField(default='Газпром футбольная программа', max_length=120, verbose_name='Подпись hero'),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='short_name',
            field=models.CharField(default='Газпром Футбол', max_length=80, verbose_name='Короткое имя'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('matchday', 'Матч-дэй'), ('training', 'Тренировка'), ('community', 'Сообщество')], max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_for',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Голы команды'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Скоро'), ('live', 'В эфире'), ('finished', 'Завершен')], default='upcoming', max_length=12),
        ),
    ]
