# Generated by Django 5.1.7 on 2026-03-31 15:56

from django.db import migrations, models


def first_text(*values):
    for value in values:
        if value is None:
            continue
        if isinstance(value, str):
            value = value.strip()
        if value != "":
            return value
    return ""


def copy_bilingual_fields(obj, field_names):
    update_fields = []
    for field_name in field_names:
        legacy = first_text(getattr(obj, field_name, ""))
        value_ru = first_text(getattr(obj, f"{field_name}_ru", ""))
        value_en = first_text(getattr(obj, f"{field_name}_en", ""))
        resolved_ru = first_text(value_ru, legacy, value_en)
        resolved_en = first_text(value_en, legacy, value_ru)
        setattr(obj, f"{field_name}_ru", resolved_ru)
        setattr(obj, f"{field_name}_en", resolved_en)
        update_fields.extend((f"{field_name}_ru", f"{field_name}_en"))
    return update_fields


def backfill_localized_fields(apps, schema_editor):
    ClubProfile = apps.get_model("club", "ClubProfile")
    Player = apps.get_model("club", "Player")
    Match = apps.get_model("club", "Match")
    NewsPost = apps.get_model("club", "NewsPost")
    Trophy = apps.get_model("club", "Trophy")
    GalleryItem = apps.get_model("club", "GalleryItem")

    for obj in ClubProfile.objects.all():
        update_fields = copy_bilingual_fields(
            obj,
            ("name", "short_name", "tagline", "mission", "city", "stadium", "address", "hero_badge", "source_name"),
        )
        obj.save(update_fields=update_fields)

    for obj in Player.objects.all():
        update_fields = copy_bilingual_fields(
            obj,
            ("full_name", "hometown", "bio", "achievements", "place_of_birth", "citizenship", "previous_club"),
        )
        obj.save(update_fields=update_fields)

    for obj in Match.objects.all():
        update_fields = copy_bilingual_fields(
            obj,
            ("opponent", "competition", "venue", "city", "summary"),
        )
        obj.save(update_fields=update_fields)

    for obj in NewsPost.objects.all():
        update_fields = copy_bilingual_fields(
            obj,
            ("title", "excerpt", "body", "source_name"),
        )
        obj.save(update_fields=update_fields)

    for obj in Trophy.objects.all():
        update_fields = copy_bilingual_fields(obj, ("title", "description"))
        obj.save(update_fields=update_fields)

    for obj in GalleryItem.objects.all():
        update_fields = copy_bilingual_fields(obj, ("title", "caption", "accent", "source_name"))
        obj.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_clubprofile_hospitality_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='address_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес (EN)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='address_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес (RU)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='city_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Город (EN)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='city_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Город (RU)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='hero_badge_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Подпись hero (EN)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='hero_badge_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Подпись hero (RU)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='mission_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание клуба (EN)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='mission_ru',
            field=models.TextField(blank=True, default='', verbose_name='Описание клуба (RU)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название клуба (EN)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название клуба (RU)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='short_name_en',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Короткое имя (EN)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='short_name_ru',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Короткое имя (RU)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='source_name_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Источник данных (EN)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='source_name_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Источник данных (RU)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='stadium_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Стадион (EN)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='stadium_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Стадион (RU)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='tagline_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Слоган (EN)'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='tagline_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Слоган (RU)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='accent_en',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Акцентный текст (EN)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='accent_ru',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Акцентный текст (RU)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='caption_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подпись (EN)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='caption_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подпись (RU)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='source_name_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Источник (EN)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='source_name_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Источник (RU)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Название (RU)'),
        ),
        migrations.AddField(
            model_name='match',
            name='city_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Город (EN)'),
        ),
        migrations.AddField(
            model_name='match',
            name='city_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Город (RU)'),
        ),
        migrations.AddField(
            model_name='match',
            name='competition_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Турнир (EN)'),
        ),
        migrations.AddField(
            model_name='match',
            name='competition_ru',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Турнир (RU)'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Соперник (EN)'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_ru',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Соперник (RU)'),
        ),
        migrations.AddField(
            model_name='match',
            name='summary_en',
            field=models.TextField(blank=True, default='', verbose_name='Краткий обзор (EN)'),
        ),
        migrations.AddField(
            model_name='match',
            name='summary_ru',
            field=models.TextField(blank=True, default='', verbose_name='Краткий обзор (RU)'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Площадка (EN)'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue_ru',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Площадка (RU)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='body_en',
            field=models.TextField(blank=True, default='', verbose_name='Текст (EN)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='body_ru',
            field=models.TextField(blank=True, default='', verbose_name='Текст (RU)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='excerpt_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Краткое описание (EN)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='excerpt_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Краткое описание (RU)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='source_name_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Источник (EN)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='source_name_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Источник (RU)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='player',
            name='achievements_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Достижения (EN)'),
        ),
        migrations.AddField(
            model_name='player',
            name='achievements_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Достижения (RU)'),
        ),
        migrations.AddField(
            model_name='player',
            name='bio_en',
            field=models.TextField(blank=True, default='', verbose_name='Профиль игрока (EN)'),
        ),
        migrations.AddField(
            model_name='player',
            name='bio_ru',
            field=models.TextField(blank=True, default='', verbose_name='Профиль игрока (RU)'),
        ),
        migrations.AddField(
            model_name='player',
            name='citizenship_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Гражданство (EN)'),
        ),
        migrations.AddField(
            model_name='player',
            name='citizenship_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Гражданство (RU)'),
        ),
        migrations.AddField(
            model_name='player',
            name='full_name_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Имя (EN)'),
        ),
        migrations.AddField(
            model_name='player',
            name='full_name_ru',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Имя (RU)'),
        ),
        migrations.AddField(
            model_name='player',
            name='hometown_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Город (EN)'),
        ),
        migrations.AddField(
            model_name='player',
            name='hometown_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Город (RU)'),
        ),
        migrations.AddField(
            model_name='player',
            name='place_of_birth_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Место рождения (EN)'),
        ),
        migrations.AddField(
            model_name='player',
            name='place_of_birth_ru',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Место рождения (RU)'),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_club_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Предыдущий клуб (EN)'),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_club_ru',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Предыдущий клуб (RU)'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='description_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Трофей (EN)'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Трофей (RU)'),
        ),
        migrations.RunPython(backfill_localized_fields, noop_reverse),
    ]
